branches:
  only:
    - master

language: python

python:
  - 2.7
  - 3.5
  - 3.8

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  coverage run --source=pyjet setup.py test

after_success:
  coveralls

notifications:
  slack: scikit-hep:b6cgBXwccPoaCNLn5VKFJFVy
