name: Main

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["2.7", "3.7", "3.8", "pypy3"]
        runs-on: [ubuntu-latest]
        include:
          - python-version: 3.7
            runs-on: windows-latest
          - python-version: 3.9
            runs-on: macos-latest

    name: Dev ${{ matrix.python-version }} • ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build and get requirements
      run: pip install .[dev]
    - name: Test
      run: pytest

  preexisting:
    name: External FastJet
    runs-on: ubuntu-latest
    container: python:3.8

    steps:
    - uses: actions/checkout@v2
    - name: Install FastJet
      run: apt-get update && apt-get install -y libfastjet-dev libfastjetplugins-dev libfastjettools-dev libcgal-dev
      # Build dependencies get --global-option! So install any that have to build first here.
    - name: Install deps that need to build
      run: pip install "setuptools>=42" "importlib-resources>=1.1" "numpy>=1.13.3" pytest "Cython~=0.29.21" wheel
    - name: Build
      run: pip install . --no-build-isolation --global-option="build_ext" --global-option="--external-fastjet"
    - name: Test
      run: pytest
